params:
  epochs: 30
  batch_size: 32
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000


artifacts:
  artifact_dir: artifacts
  model_dir: model
  plot_dir: plots
  checkpoint_dir: checkpoints

logs:
  log_dir: logs
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs  