params:
  epochs: 10
  batch_size: 32
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000
  patience: 5
  restore_best_weights: True
  save_best_only: True


artifacts:
  artifact_dir: artifacts
  model_dir: model
  plot_dir: plots
  checkpoint_dir: checkpoints
  model_name: model.h5

logs:
  log_dir: logs
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs  